import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { logout } from '@/app/login/actions';

export default async function AdminPage() {
  const supabase = await createClient();
  const { data } = await supabase.auth.getClaims();
  if (!data?.claims?.sub) redirect('/login');

  const userId = String(data.claims.sub);
  const { data: profile } = await supabase
    .from('profiles')
    .select('full_name, role, active')
    .eq('id', userId)
    .maybeSingle();

  if (!profile?.active) {
    await supabase.auth.signOut();
    redirect('/login?error=Your%20account%20is%20inactive');
  }

  if (profile.role !== 'admin') redirect('/dashboard');

  const [{ count: productsCount }, { count: packagesCount }, { count: resellerCount }] = await Promise.all([
    supabase.from('products').select('*', { count: 'exact', head: true }).eq('active', true),
    supabase.from('packages').select('*', { count: 'exact', head: true }).eq('active', true),
    supabase.from('profiles').select('*', { count: 'exact', head: true }).eq('role', 'reseller').eq('active', true),
  ]);

  return (
    <main className="adminPage">
      <div className="adminWrap">
        <header className="dashboardTopbar">
          <a href="/" className="brand">
            <span className="brandMark"><b>J</b><strong>BE</strong><i /></span>
            <span><b>JBE</b><small>Digital + Gaming</small></span>
          </a>
          <div className="dashboardTopActions">
            <span className="roleBadge">ADMIN</span>
            <form action={logout}><button className="logoutBtn" type="submit">Sign out</button></form>
          </div>
        </header>

        <section className="adminHero">
          <div>
            <span className="miniLabel">JBE ADMIN PORTAL</span>
            <h1>Business control center.</h1>
            <p>Manage your JBE catalog, pricing and reseller accounts from one place.</p>
          </div>
          <a href="/dashboard" className="backBtn">← Reseller view</a>
        </section>

        <section className="adminStats">
          <div><span>ACTIVE PRODUCTS</span><b>{productsCount ?? 0}</b><small>Products in catalog</small></div>
          <div><span>ACTIVE PACKAGES</span><b>{packagesCount ?? 0}</b><small>Available packages</small></div>
          <div><span>ACTIVE RESELLERS</span><b>{resellerCount ?? 0}</b><small>Managed accounts</small></div>
        </section>

        <section className="adminTools">
          <div className="adminToolCard">
            <div className="adminToolIcon">P</div>
            <span className="miniLabel">CATALOG</span>
            <h2>Products & packages</h2>
            <p>Add, edit or deactivate products and packages.</p>
            <a className="adminPrimaryBtn" href="/admin/catalog">Manage catalog →</a>
          </div>

          <div className="adminToolCard">
            <div className="adminToolIcon">$</div>
            <span className="miniLabel">PRICING</span>
            <h2>B2C & reseller prices</h2>
            <p>Maintain customer and reseller pricing in one place.</p>
            <button className="adminDisabledBtn" disabled>Coming next</button>
          </div>

          <div className="adminToolCard">
            <div className="adminToolIcon">U</div>
            <span className="miniLabel">ACCOUNTS</span>
            <h2>Reseller accounts</h2>
            <p>Create, activate or deactivate reseller access.</p>
            <button className="adminDisabledBtn" disabled>Coming next</button>
          </div>

          <div className="adminToolCard">
            <div className="adminToolIcon">I</div>
            <span className="miniLabel">INVOICES</span>
            <h2>Invoice management</h2>
            <p>View and manage invoices generated by the system.</p>
            <button className="adminDisabledBtn" disabled>Coming next</button>
          </div>
        </section>

        <footer className="dashboardFooter">
          <span>JBE Digital + Gaming</span>
          <span>Admin-only control center</span>
        </footer>
      </div>
    </main>
  );
}
